version: '3.8'

services:
  db: 
    image: mysql:8.1-oracle
    restart: always
    container_name: passenger-microservice
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /db/mysql:/var/lib/mysql